# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "owncloud"
  config.vm.box_url   = "https://github.com/Ubiwhere/vagrant-boxes/releases/download/v1.0/owncloud.box"
  config.vm.hostname = "owncloud"

  # When using owncloud at http://localhost:8080
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  # This is for Postgresql database ssh connection
  config.vm.network :forwarded_port, guest: 5432, host: 65432
  config.vm.provision :shell, :path => "vagrant_provision/bootstrap.sh"

  # Create a private network, which allows host-only access to the machine using a specific IP.
  config.vm.network :private_network, ip: "10.0.0.100"

  # Fixes https://github.com/mitchellh/vagrant/issues/3341#issuecomment-144271026
  config.vbguest.auto_update = false

  # ensure there's enough RAM/CPU
  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
  end

  # Fixes this issue http://stackoverflow.com/q/33442898/977622
  config.vm.synced_folder ".", "/var/www", owner: "www-data", group: "www-data", mount_options: ["dmode=770,fmode=770"]

  # Fixes this issue https://github.com/mitchellh/vagrant/issues/5186
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

end
